version: '3.7'
services:
  server:
    container_name: server-dev
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - PORT = ${PORT}
    ports:
      - 3000:${PORT}
    env_file:
      - .env
    volumes:
      - ./:/usr/local/apps/server/dev
      - ignore:/usr/local/apps/server/dev/node_modules
    depends_on:
      - db
volumes:
  ignore: