FROM node:22-alpine
WORKDIR /usr/local/apps/server

COPY package.json ./
RUN npm install && npm cache clean --force
ENV PATH=/usr/local/apps/server/node_modules/.bin:$PATH

WORKDIR /usr/local/apps/server/dev
COPY tsconfig.json ./

COPY src ./src
COPY .env ./

EXPOSE ${PORT}

CMD ["npm", "run", "start:watch"]